# Generated by Django 5.0 on 2023-12-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voter_email',
            field=models.EmailField(max_length=254),
        ),
    ]
